export const ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  VALIDATION_ERROR: 'VALIDATION_ERROR',

  NOT_FOUND: 'NOT_FOUND',

  UNAUTHORIZED: 'UNAUTHORIZED',

  FORBIDDEN: 'FORBIDDEN',

  CONFLICT: 'CONFLICT',

  BAD_REQUEST: 'BAD_REQUEST',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
