name: Docker

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  docker:
    name: Build Docker Image

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: node-express-ts-starter:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
